spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/graduate-order?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username:  root
    password: x5
    driver-class-name:  com.mysql.jdbc.Driver
    type:  com.alibaba.druid.pool.DruidDataSource

server:
  port: 8089
